### ISSUE TITLE
Controlling the length of output

### ISSUE THREAD

**Issue by aretius** [ucfnlp/control-over-copying#1]
Hey all,
Loved reading your paper and was quite interested in the approach of copying while summarising as it should leave better results

I was wondering if it's possible to control the output length both during `Predictions` and `Finetuning` through some config file?

**Comment by KaiQiangSong** [comment]
During the Searching, you could all answers with length(count by token) you need. Sometimes you may not get an answer with Beam Searching because beam size is small, try larger beam size or Best-First Searching.
