### ISSUE TITLE
Is it possible to control amount of copying?

### ISSUE THREAD

**Issue by aretius** [ucfnlp/control-over-copying#2]
Hey all,

I tried generating outputs of the following input through all available datasources:
`Hailey Baldwin has this to say after being accused of throwing shade at Selena Gomez's new song.`
but the output was 
`Alec Baldwin accused of throwing shade at Selena Gomez`.

Although the output is not correct, however what concerns me is the word `Alec` being present. 
Any thoughts on this?

**Comment by KaiQiangSong** [comment]
This is about the hallucination. Because we use Bert as our pre-trained model. It could introduce some knowledge from the pre-training data. Actually almost every abstractive summarization has this issue. We are finding a way to solve it.
