### ISSUE TITLE
How to preprocess data ?

### ISSUE THREAD

**Issue by astariul** [ucfnlp/control-over-copying#4]
Thanks for open-sourcing your code :)

I would like to know **how you preprocess the dataset ?**  
Is it included in your repository ? I couldn't find the script.

The path of the dataset is referred in the settings :

https://github.com/ucfnlp/control-over-copying/blob/b86910deff90b391456be86bb69e9d3811a6cc10/settings/dataset/cnn_dailymail.json#L12

But this path is not in the repository. How can I process the data by myself to get the data in the right format and everything ?

---

The motivation behind this question is that I would like to know how you classified each word of the summary as `seen` or `unseen`.  
In your paper you mentioned `copy rate` as 

>the percentage of summary n-grams appearing in the source text

Did you use 1-grams ? 2-grams ? Any other n-grams ? A mix of all this ?

_Thanks for your time :)_

**Comment by astariul** [comment]
Nevermind, I didn't read the paper carefully enough, you mentioned it :

>We define copy rate as the percentage of summary n-grams appearing
in the source text, where n=1/2/3/4 as well as an average of them

I'm still confused : this `copy rate` is for the whole summary, right ?  
How did you defined a single word as `seen` or `unseen` ?

**Comment by KaiQiangSong** [comment]
"seen" tokens are tokens(word piece in BPE tokenizer) that appear in the original text.
"unseen" tokens are those tokens that don't appear in the original text.
Copy rate measures of the exact copy of n-gram from the original.
It is n-copied-n-gram / total n-gram of summary.
