### ISSUE TITLE
Similar prob and Similar threshold

### ISSUE THREAD

**Issue by Egojr** [ucfnlp/control-over-copying#5]
Hello,

I have been training the model with a Japanese BERT and the results are really good! I wanted to ask about an explanation about the similar prob and similar threshold parameters when training. 

From my understanding the the parameters that control extractive/abstractive behaviour are seen prob and unseen prob, however do these two other parameters help in controlling the model's copy rate?

Thank you

**Comment by KaiQiangSong** [comment]
Hi Egojr, 

Thanks for the questions. In the paper, we divide the target side tokens into 2 categories (Seen and Unseen). However, you could divide them into more fine-grained ones. (Seen tokens, Similar Unseen Tokens, Unsimilar Unseen tokens) for the better control of abstraction.  We define a Similar Unseen Token as a target token that could find a most similar token in the source side that their cosine similarity is above the threshold.

I believe, by distinguishing similar or not we could help with the abstractive generation part. It is not mentioned in the paper. It could be an extension of future directions.

**Comment by Egojr** [comment]
I understand, I'll try experimenting with them and see the results. Thank you very much for your answer and for the work in this paper.
