### ISSUE TITLE
A question about L_pred in soft-bounded word reward

### ISSUE THREAD

**Issue by elevenofji** [ucfnlp/control-over-copying#9]
Hi,
In your paper you said that "We obtain the predicted length L_pred using greedy search" in _soft-bounded word reward_, could you please give me an illstrustration about the "greedy search" to get the L_pred?

**Comment by KaiQiangSong** [comment]
Greedy Search is a method for decoding the sequence. It means that you pick the token with the highest probability for each time and finish decoding when there's a special [END] token.
